services:
  takigrapher:
    image: luizhp/takigrapher:latest
    container_name: takigrapher
    restart: unless-stopped
    environment:
      - TZ=America/Sao_Paulo
      - PYTHONUNBUFFERED=1
    volumes:
      # Uncomment the line below to mount your music directory
      # - "/mnt/music/:/app/media/"
      - "./data/whisper/cache:/root/.cache/whisper" 
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    tty: true
    stdin_open: true
    networks:
      - takigrapher-net

networks:
  takigrapher-net:
    name: takigrapher-net
    driver: bridge
