services:
  takigrapher:
    image: luizhp/takigrapher:latest
    container_name: takigrapher
    restart: unless-stopped
    environment:
      - TZ=America/Sao_Paulo
      - PYTHONUNBUFFERED=1
    volumes:
      - "/mnt/music/:/app/media/"
      - "./data/whisper/cache:/root/.cache/whisper" 
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1 # all
              capabilities: [gpu]
    tty: true
    stdin_open: true
    networks:
      - takigrapher-net

networks:
  takigrapher-net:
    name: takigrapher-net
    driver: bridge
